# -*- coding: utf-8 -*-
"""madhu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PNJKk4E6DP5qB1MfSzCUsh8P7SNOaO1c
"""

import numpy as np # scientific computation
import pandas as pd # Loading dataset file
import matplotlib.pyplot as plt # Visulization
import nltk # Preprocessing our text
from nltk.corpus import stopwords # removing all the stop words
from nltk.stem.porter import PorterStemmer # stemming of words

#Load our dataset
df=pd.read_csv("spam.csv",encoding="Latin")
df.head()

#Give concise summary of a DataFrame
df.info()

#Returns the sum fo all values
df.isna().sum()

# bottom 5 rows of the dataframe
df. tail()

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['v1'] = le.fit_transform(df['v1'])

nltk.download("stopwords")

import nltk

import re

import re